# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Castle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('host', models.GenericIPAddressField(default='0.0.0.0', protocol='IPv4', unique=True)),
                ('gatekeeper', models.GenericIPAddressField(default='0.0.0.0', protocol='IPv4', unique=True)),
                ('user', models.GenericIPAddressField(blank=True, editable=False, null=True, protocol='IPv4')),
                ('taken_at', models.DateTimeField(editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=20, unique=True)),
                ('inside_port', models.PositiveSmallIntegerField(default=22, verbose_name='room_port')),
                ('outside_port', models.PositiveSmallIntegerField(default=9022, verbose_name='gate_port')),
            ],
        ),
        migrations.AddField(
            model_name='castle',
            name='rooms',
            field=models.ManyToManyField(to='castles.Room'),
        ),
    ]
