# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('castles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='castle',
            name='alias',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
